- name: Run apt-get update
  apt:
    update_cache: yes
  tags:
    - common

- name: Install extra packages
  apt:
    name: "{{ item }}"
    state: present
  loop: 
  - "{{ extra_packages }}"
  tags:
    - common

- name: Setting OS version fact
  set_fact:
    osversion: "{{ ansible_distribution | lower }}{{ ansible_distribution_major_version }}"
  tags:
    - common

- name: Check OS version
  fail:
    msg: "OS Version( {{ ansible_distribution }}{{ ansible_distribution_major_version }} ) is not certified for the role"
  vars:
    rel: "{{ os_release }}" # added this var to workaround jinja2 delimiter warning
  when:
    - osversion != rel
  tags:
    - common

- name: Configure hostname resolution via /etc/hosts
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*{{ item }}$' 
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" 
    state: present
    backup: yes
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"
  tags:
    - common