virtualization_packages:
  - qemu-kvm
  - libvirt-daemon-system
  - libvirt-clients
  - bridge-utils
  - virt-manager
  - python-lxml
  - cloud-image-utils
  - virtinst
  - uvtool

uvtool_images:
  - trusty
  - xenial
  - bionic
  - focal

img_arch: amd64  # uvtool images architecture