- name: Upload cluster init config file
  template:
    src: templates/cluster-conf.yaml.j2
    dest: "/home/{{ ansible_user }}/cluster-conf.yaml"

- name: Initialize the cluster using kubeadm
  shell: |
    kubeadm init --config=/home/{{ ansible_user }}/cluster-conf.yaml

- name: Setup cluster config on master node
  shell: |
    mkdir -p /home/{{ ansible_user }}/.kube
    cp -i /etc/kubernetes/admin.conf /home/{{ ansible_user }}/.kube/config
    chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config

- name: Generate join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: Copy join command
  become: false
  local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="/tmp/join"

- name: Enable kubectl autocompletion
  shell:
    cmd: kubectl completion bash > /etc/bash_completion.d/kubectl
    # If you do not want to run this when the file already exists, add
    creates: /etc/bash_completion.d/kubectl

- name: Deploy Calico CNI
  become: false
  command: >
    kubectl --kubeconfig /home/{{ ansible_user }}/.kube/config apply -f
    https://docs.projectcalico.org/manifests/calico.yaml
  when: network == "calico"

- name: Allow pods on master node (if configured).
  become: false
  command: "kubectl taint nodes --all node-role.kubernetes.io/master:NoSchedule-"
  vars:
    pods_on_master: "{{ allow_pods_on_master }}"
  when:
    - pods_on_master == true

- name: Check if Kubernetes Dashboard UI service exists.
  become: false
  shell: kubectl get services --namespace kube-system | grep -q kubernetes-dashboard
  changed_when: false
  failed_when: false
  register: dashboard_service
  when: enable_web_ui | bool

- name: Enable the Kubernetes Web Dashboard UI (if configured).
  become: false
  command: "kubectl apply -f https://raw.githubusercontent.com/kubernetes/dashboard/{{ dashboard_version }}/aio/deploy/recommended.yaml"
  when:
    - enable_web_ui | bool
    - dashboard_service.rc != 0