- name: Run common tasks on all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Set up SSH access
  hosts: all
  become: yes
  roles:
    - ssh

- name: Set up hypervisor nodes
  hosts: hypervisors
  become: yes
  roles:
    - hypervisor

