- name: Run common tasks on all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Set up SSH access
  hosts: all
  become: yes
  roles:
    - ssh

- name: Set up hypervisor nodes
  hosts: hypervisors
  become: yes
  roles:
    - hypervisor

- name: Initial Kubernetes tasks and configs
  hosts: kubernetes
  become: true
  gather_facts: true
  roles:
    - kubernetes-common

- name: Install and configure Kubernetes master nodes
  hosts: masters
  become: true
  gather_facts: true
  roles:
    - kubernetes-master

- name: Install and configure Kubernetes worker nodes
  hosts: workers
  become: true
  gather_facts: true
  roles:
    - kubernetes-worker